"""add: projects, projects_users

Revision ID: 96964ef2cdec
Revises: a4a6804f2cf0
Create Date: 2021-03-05 12:16:31.146633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96964ef2cdec'
down_revision = 'a4a6804f2cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects_users',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_users')
    op.drop_table('projects')
    # ### end Alembic commands ###
